"""Claim CRUD + active-state queries.

Pure storage layer — no LLMs, no embeddings. Validation that belongs here
(per `gt_v2_study_notes.md` §2.2):

- `predicate ∈ PREDICATE_FAMILIES` — closed clinical vocabulary.
- `0 <= confidence <= 1`.
- `source_turn_id` must reference an existing row in `turns`.
- Non-empty `subject` and `value`.

Invalid claims raise `ClaimValidationError` — never silently drop
(rules.md §3.1 anti-pattern).
"""
from __future__ import annotations

import sqlite3
import uuid
from collections.abc import Iterable
from time import time_ns

import structlog

from src.substrate.schema import PREDICATE_FAMILIES, Claim, ClaimStatus, Turn

log = structlog.get_logger(__name__)


class ClaimValidationError(ValueError):
    """Raised when a claim fails write-time validation.

    Rules.md §4.1: "A claim with an empty or invalid `source_turn_id` is
    rejected at write time." This is the error we raise.
    """


# ---------------------------------------------------------------- helpers ---


# Process-local monotonic counter to tie-break `time_ns()` on platforms where
# the clock resolution is coarse (Windows: ~1 ms). Two inserts in the same
# millisecond would otherwise share `created_ts` and collide on
# "most recent" tie-breaks. We track the last-emitted value and bump by 1 ns
# when wall-clock would collide — this keeps values monotonically increasing
# without overflowing SQLite's 64-bit INTEGER.
_last_ts: list[int] = [0]


def now_ns() -> int:
    """Strictly-increasing nanosecond timestamp.

    Wall-clock `time_ns()` unless doing so would not strictly increase since
    the last call, in which case we bump by 1 ns. Good enough for ordering
    within a run; not an external clock source.
    """
    wall = time_ns()
    next_ts = wall if wall > _last_ts[0] else _last_ts[0] + 1
    _last_ts[0] = next_ts
    return next_ts


def new_claim_id() -> str:
    """Server-assigned claim id. Prefix `cl_` keeps logs grep-friendly."""
    return f"cl_{uuid.uuid4().hex[:12]}"


def new_turn_id() -> str:
    """Server-assigned turn id. Prefix `tu_` keeps logs grep-friendly."""
    return f"tu_{uuid.uuid4().hex[:12]}"


def row_to_claim(row: sqlite3.Row) -> Claim:
    """Map a sqlite3.Row from `claims` into the typed `Claim` dataclass.

    Hydrates `valid_from_ts` / `valid_until_ts` if the row carries them.
    Older rows (or test fixtures using subset-column SELECT) gracefully
    fall back to None — both fields default to None on the dataclass.
    """
    # `sqlite3.Row` lacks a `.get()`. Use `keys()` to detect column presence
    # so callers passing a narrower SELECT don't trip a KeyError.
    keys = set(row.keys())
    return Claim(
        claim_id=row["claim_id"],
        session_id=row["session_id"],
        subject=row["subject"],
        predicate=row["predicate"],
        value=row["value"],
        value_normalised=row["value_normalised"],
        confidence=row["confidence"],
        source_turn_id=row["source_turn_id"],
        status=ClaimStatus(row["status"]),
        created_ts=row["created_ts"],
        char_start=row["char_start"],
        char_end=row["char_end"],
        valid_from_ts=row["valid_from_ts"] if "valid_from_ts" in keys else None,
        valid_until_ts=row["valid_until_ts"] if "valid_until_ts" in keys else None,
    )


def _normalise_subject(subject: str) -> str:
    """Subject-first canonical form per gt_v2_study_notes §3.3.

    Lowercase, strip whitespace, collapse internal runs to a single
    underscore. "Patient Doe" -> "patient_doe".
    """
    import re

    cleaned = subject.strip().lower()
    cleaned = re.sub(r"\s+", "_", cleaned)
    return cleaned


# --------------------------------------------------------------- turns CRUD ---


def insert_turn(conn: sqlite3.Connection, turn: Turn) -> None:
    """Insert a turn. No validation beyond the schema CHECKs.

    Turn IDs should be pre-generated by the caller (usually
    `on_new_turn.on_new_turn`). Duplicate IDs raise `sqlite3.IntegrityError`.
    """
    conn.execute(
        "INSERT INTO turns (turn_id, session_id, speaker, text, ts, asr_confidence)"
        " VALUES (?, ?, ?, ?, ?, ?)",
        (
            turn.turn_id,
            turn.session_id,
            turn.speaker.value,
            turn.text,
            turn.ts,
            turn.asr_confidence,
        ),
    )
    log.debug(
        "substrate.turn_inserted",
        session_id=turn.session_id,
        turn_id=turn.turn_id,
        speaker=turn.speaker.value,
    )


def get_turn(conn: sqlite3.Connection, turn_id: str) -> Turn | None:
    row = conn.execute(
        "SELECT turn_id, session_id, speaker, text, ts, asr_confidence"
        " FROM turns WHERE turn_id = ?",
        (turn_id,),
    ).fetchone()
    if row is None:
        return None
    from src.substrate.schema import Speaker  # local import avoids cycle

    return Turn(
        turn_id=row["turn_id"],
        session_id=row["session_id"],
        speaker=Speaker(row["speaker"]),
        text=row["text"],
        ts=row["ts"],
        asr_confidence=row["asr_confidence"],
    )


# -------------------------------------------------------------- claims CRUD ---


def validate_claim(
    *,
    subject: str,
    predicate: str,
    value: str,
    confidence: float,
    source_turn_id: str,
    char_start: int | None,
    char_end: int | None,
    turn_text_len: int | None = None,
) -> None:
    """Write-time validation. Raises `ClaimValidationError` on any violation.

    Predicate validation consults the **active pack** (env `ACTIVE_PACK`)
    rather than the schema-level chest-pain default — that schema set
    predates the pack abstraction and would silently drop every
    personal_assistant claim during a LongMemEval run. Falls back to the
    schema set if active_pack() raises (e.g., test environment with no
    pack configured).
    """
    if not subject or not subject.strip():
        raise ClaimValidationError("subject must be non-empty")
    try:
        from src.substrate.predicate_packs import active_pack

        allowed = active_pack().predicate_families
    except Exception:  # noqa: BLE001 — fallback keeps tests passing
        allowed = PREDICATE_FAMILIES
    if predicate not in allowed:
        raise ClaimValidationError(
            f"predicate {predicate!r} not in closed family (active pack); "
            f"allowed = {sorted(allowed)}"
        )
    if not value or not value.strip():
        raise ClaimValidationError("value must be non-empty")
    if not (0.0 <= confidence <= 1.0):
        raise ClaimValidationError(f"confidence {confidence} outside [0, 1]")
    if not source_turn_id:
        raise ClaimValidationError("source_turn_id must be non-empty (rules.md §4.1)")

    if char_start is not None or char_end is not None:
        if char_start is None or char_end is None:
            raise ClaimValidationError(
                "char_start and char_end must either both be set or both be None"
            )
        if char_start < 0 or char_end < char_start:
            raise ClaimValidationError(
                f"invalid span ({char_start}, {char_end}); require 0 <= start <= end"
            )
        if turn_text_len is not None and char_end > turn_text_len:
            raise ClaimValidationError(
                f"char_end {char_end} exceeds source turn length {turn_text_len}"
            )


def insert_claim(
    conn: sqlite3.Connection,
    *,
    session_id: str,
    subject: str,
    predicate: str,
    value: str,
    confidence: float,
    source_turn_id: str,
    value_normalised: str | None = None,
    char_start: int | None = None,
    char_end: int | None = None,
    claim_id: str | None = None,
    status: ClaimStatus = ClaimStatus.ACTIVE,
    valid_from: int | None = None,
    valid_until: int | None = None,
) -> Claim:
    """Insert a new claim after validation.

    Checks that `source_turn_id` refers to an existing turn (rules.md §4.1).
    Returns the persisted `Claim` with its server-assigned id + timestamp.

    Temporal validity defaults: `valid_from` defaults to `created_ts` (claim
    is valid from creation onward); `valid_until` defaults to None (unbounded
    until supersession or explicit narrowing). Pass-1 supersession will
    later set `valid_until_ts` on the superseded claim — see
    `src/substrate/supersession.py::detect_pass1`.
    """
    turn = get_turn(conn, source_turn_id)
    if turn is None:
        raise ClaimValidationError(
            f"source_turn_id {source_turn_id!r} does not reference any turn"
        )
    validate_claim(
        subject=subject,
        predicate=predicate,
        value=value,
        confidence=confidence,
        source_turn_id=source_turn_id,
        char_start=char_start,
        char_end=char_end,
        turn_text_len=len(turn.text),
    )

    cid = claim_id or new_claim_id()
    ts = now_ns()
    valid_from_ts = ts if valid_from is None else valid_from
    valid_until_ts = valid_until
    if valid_until_ts is not None and valid_until_ts <= valid_from_ts:
        raise ClaimValidationError(
            f"valid_until ({valid_until_ts}) must be > valid_from ({valid_from_ts})"
        )
    norm_subject = _normalise_subject(subject)
    conn.execute(
        "INSERT INTO claims (claim_id, session_id, subject, predicate, value,"
        " value_normalised, confidence, source_turn_id, status, created_ts,"
        " char_start, char_end, valid_from_ts, valid_until_ts)"
        " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (
            cid,
            session_id,
            norm_subject,
            predicate,
            value,
            value_normalised,
            confidence,
            source_turn_id,
            status.value,
            ts,
            char_start,
            char_end,
            valid_from_ts,
            valid_until_ts,
        ),
    )
    log.info(
        "substrate.claim_inserted",
        session_id=session_id,
        claim_id=cid,
        subject=norm_subject,
        predicate=predicate,
        confidence=confidence,
    )
    return Claim(
        claim_id=cid,
        session_id=session_id,
        subject=norm_subject,
        predicate=predicate,
        value=value,
        value_normalised=value_normalised,
        confidence=confidence,
        source_turn_id=source_turn_id,
        status=status,
        created_ts=ts,
        char_start=char_start,
        char_end=char_end,
        valid_from_ts=valid_from_ts,
        valid_until_ts=valid_until_ts,
    )


def get_claim(conn: sqlite3.Connection, claim_id: str) -> Claim | None:
    row = conn.execute(
        "SELECT * FROM claims WHERE claim_id = ?", (claim_id,)
    ).fetchone()
    return row_to_claim(row) if row is not None else None


def set_claim_status(
    conn: sqlite3.Connection, claim_id: str, status: ClaimStatus
) -> None:
    cur = conn.execute(
        "UPDATE claims SET status = ? WHERE claim_id = ?", (status.value, claim_id)
    )
    if cur.rowcount == 0:
        raise ClaimValidationError(f"claim {claim_id!r} not found")
    log.info(
        "substrate.claim_status_set",
        claim_id=claim_id,
        status=status.value,
    )


def list_active_claims(
    conn: sqlite3.Connection, session_id: str
) -> list[Claim]:
    """All claims in the session with status in {active, confirmed}.

    Superseded and dismissed claims are excluded. `confirmed` is a stronger
    "active" — still visible to projections.
    """
    rows = conn.execute(
        "SELECT * FROM claims WHERE session_id = ?"
        " AND status IN ('active','confirmed')"
        " ORDER BY created_ts ASC",
        (session_id,),
    ).fetchall()
    return [row_to_claim(r) for r in rows]


def list_claims_for_turn(conn: sqlite3.Connection, turn_id: str) -> list[Claim]:
    rows = conn.execute(
        "SELECT * FROM claims WHERE source_turn_id = ? ORDER BY created_ts ASC",
        (turn_id,),
    ).fetchall()
    return [row_to_claim(r) for r in rows]


def get_superseded_by(
    conn: sqlite3.Connection, claim_id: str
) -> str | None:
    """Return the `new_claim_id` that supersedes `claim_id`, or None.

    Derived view over `supersession_edges` — the edge table is canonical;
    this function is the read-time accessor (per
    `advisory/validation/architecture_validation.md` §4: "derived `superseded_by`
    accessor (vs stored field)"). If multiple edges exist for the same
    `old_claim_id`, returns the most recent by `created_ts` (deterministic
    tie-break by edge_id ordering when timestamps collide).
    """
    row = conn.execute(
        "SELECT new_claim_id FROM supersession_edges"
        " WHERE old_claim_id = ?"
        " ORDER BY created_ts DESC, edge_id DESC LIMIT 1",
        (claim_id,),
    ).fetchone()
    return row["new_claim_id"] if row is not None else None


def find_same_identity_claim(
    conn: sqlite3.Connection,
    *,
    session_id: str,
    subject: str,
    predicate: str,
    exclude_claim_ids: Iterable[str] = (),
) -> Claim | None:
    """Return the newest ACTIVE/CONFIRMED claim with matching (subject, predicate).

    Used by Pass-1 supersession (`supersession.detect_pass1`). The subject is
    compared against the already-normalised form stored in the DB.
    """
    excluded = tuple(exclude_claim_ids)
    placeholders = ",".join("?" * len(excluded)) if excluded else "''"
    norm = _normalise_subject(subject)
    sql = (
        "SELECT * FROM claims WHERE session_id = ? AND subject = ? AND predicate = ?"
        " AND status IN ('active','confirmed')"
        f" AND claim_id NOT IN ({placeholders})"
        " ORDER BY created_ts DESC LIMIT 1"
    )
    row = conn.execute(sql, (session_id, norm, predicate, *excluded)).fetchone()
    return row_to_claim(row) if row is not None else None
